#include<stdio.h>
#define PREFIX_MACRO my_
#define ID_MACRO     123

#define CONCAT_BAD(a, b) a##b
#define CONCAT_GOOD(a,b) CONCAT_BAD(a,b)

#define CSTR(X) #X
#define CCSTR(X) CSTR(X)

int main(){
    printf("CSTR(CONCAT_BAD(PREFIX_MACRO,ID_MACRO)):"CSTR(CONCAT_BAD(PREFIX_MACRO,ID_MACRO))"\n");
    printf("CCSTR(CONCAT_BAD(PREFIX_MACRO,ID_MACRO)):"CCSTR(CONCAT_BAD(PREFIX_MACRO,ID_MACRO))"\n");
    printf("CSTR(CONCAT_GOOD(PREFIX_MACRO,ID_MACRO)):"CSTR(CONCAT_GOOD(PREFIX_MACRO,ID_MACRO))"\n");
    printf("CCSTR(CONCAT_GOOD(PREFIX_MACRO,ID_MACRO)):"CCSTR(CONCAT_GOOD(PREFIX_MACRO,ID_MACRO))"\n");
    return 0;
}
